import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftSideBar from "@/components/sidebar/LeftSideBar";
import Header from "@/components/header/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
        >
        {/* full height, no body scroll */}
        <div className="flex flex-col h-full">
          {/* fixed height header */}
          <Header />

          {/* main layout: sidebar + scrollable content */}
          <div className="flex flex-1 overflow-hidden">
            <LeftSideBar />

            {/* only this part scrolls */}
            <div className="flex-1 overflow-y-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
